language: go

go_import_path: github.com/guitarpawat/wsp-ecommerce


env:
  global:
    - JYTHON=false
    - DISPLAY=':99.0'

branches:
  only:
  - /.*/

stages:
  - "Backend Test"
  - "Frontend Test"

jobs:
  include:
    - stage: "Backend Test"
      go: "1.10.x"
      go: "1.11.x"
      script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "Frontend Test"
      go: "1.10.x"
      services: mongodb
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_install:
        - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
        - sudo wget --no-verbose http://chromedriver.storage.googleapis.com/$CDVERSION/chromedriver_linux64.zip
        - sudo unzip chromedriver_linux64.zip
        - sudo chmod u+x chromedriver
        - sudo mv chromedriver /usr/bin/
        - sudo chmod 777 /usr/bin/chromedriver
        - sudo -H pip install -r requirements.txt
        - sudo mkdir /usr/local/share/ca-certificates/solid
        - sudo cp ssl/server.crt /usr/local/share/ca-certificates/solid/server.crt
        - sudo chmod 755 /usr/local/share/ca-certificates/solid
        - sudo chmod 644 /usr/local/share/ca-certificates/solid/server.crt
        - sudo dpkg-reconfigure ca-certificates
        - sudo update-ca-certificates
        - go get -t -v ./...
        - go run main.go -env=CI &
        - google-chrome-stable --no-sandbox --ignore-certificate-errors --headless --window-size=1920,1080 --disable-gpu --disable-dev-shm-usage --remote-debugging-port=51232 http://localhost:8000 &
      script: robot tests.robot
      