language: go

go:
  - 1.10.x
  # - 1.11.x

go_import_path: github.com/guitarpawat/wsp-ecommerce

services: mongodb

env:
  global:
    - JYTHON=false
    - DISPLAY=':99.0'

branches:
  only:
  - /.*/

jobs:
  include:
    # - stage: Backend Test
    #   script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
    - stage: Frontend Test
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_install:
      - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
      - sudo wget --no-verbose http://chromedriver.storage.googleapis.com/$CDVERSION/chromedriver_linux64.zip
      - sudo unzip chromedriver_linux64.zip
      - sudo chmod u+x chromedriver
      - sudo mv chromedriver /usr/bin/
      - sudo chmod 777 /usr/bin/chromedriver
      - sudo -H pip install -r requirements.txt
      - sudo mkdir /usr/local/share/ca-certificates/solid
      - sudo cp ssl/server.crt /usr/local/share/ca-certificates/solid/server.crt
      - sudo chmod 755 /usr/local/share/ca-certificates/solid
      - sudo chmod 644 /usr/local/share/ca-certificates/solid/server.crt
      - sudo dpkg-reconfigure ca-certificates
      - sudo update-ca-certificates
      - go get -t -v ./...
      - go run main.go &
      - google-chrome-stable --no-sandbox --headless --window-size=3200,1800 --disable-gpu --disable-dev-shm-usage --remote-debugging-port=51232 https://localhost:4433 &
      script: robot tests.robot
      