language: go

go_import_path: github.com/guitarpawat/wsp-ecommerce

env:
  global:
    - JYTHON=false
    - DISPLAY=':99.0'

branches:
  only:
  - /.*/

go:
  - "1.10.x"
  - "1.11.x"

services: mongodb

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - sudo wget --no-verbose http://chromedriver.storage.googleapis.com/$CDVERSION/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - sudo chmod 777 /usr/bin/chromedriver

install:
  - go get -t -v ./...
  - sudo -H pip install -r requirements.txt

after_install: skip

before_script:
  - go run main.go -env=CI &
  - google-chrome-stable --no-sandbox --ignore-certificate-errors --headless --window-size=1920,1080 --disable-gpu --disable-dev-shm-usage --remote-debugging-port=51232 http://localhost:8000 &

script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
name: "Backend Test"

script: robot tests.robot
name: "Frontend Test"

after_script: skip

after_success:
  - bash <(curl -s https://codecov.io/bash)
