language: go

go:
  - 1.10.x
  # - 1.11.x

go_import_path: github.com/guitarpawat/wsp-ecommerce

services: mongodb

env:
  global:
    - JYTHON=false
    - DISPLAY=':99.0'

branches:
  only:
  - /.*/
 

jobs:
  include:
    # - stage: Backend Test
    #   script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
    - stage: Frontend Test
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_install:
      - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
      - sudo wget --no-verbose http://chromedriver.storage.googleapis.com/$CDVERSION/chromedriver_linux64.zip
      - sudo unzip chromedriver_linux64.zip
      - sudo chmod u+x chromedriver
      - sudo mv chromedriver /usr/bin/
      - sudo chmod 777 /usr/bin/chromedriver
      - sudo -H pip install -r requirements.txt
      - go get -t -v ./...
      - go run main.go &
      - google-chrome-stable --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 https://localhost:4433 &
      script: robot tests.robot
      