language: go

go:
  - 1.10.x
  - 1.11.x

go_import_path: github.com/guitarpawat/wsp-ecommerce

services: mongodb

env:
  global:
    - JYTHON=false

branches:
  only:
  - /.*/

before_install:
  - go get -t -v ./...

jobs:
  include:
    - stage: Backend Test
      script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    - stage: Frontend Test
      before_install:
      - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
      - wget --no-verbose http://chromedriver.storage.googleapis.com/$CDVERSION/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - sudo chmod u+x chromedriver
      - sudo mv chromedriver /usr/bin/
      - sudo apt-get install python3
      - sudo apt-get install python3-pip
      - sudo apt-get install google-chrome-stable
      - sudo pip3 install urllib3
      - sudo pip3 install -r requirements.txt
      - go run main.go &
      script: robot tests.robot
      

after_success:
  - bash <(curl -s https://codecov.io/bash)
